services:
  - type: web
    name: physio-client
    env: static
    buildCommand: npm run build
    envVars:
      - key: VITE_PUBLIC_SITE_URL
        value: https://nearbyphysio.com
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html